# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file_date', models.DateField(blank=True, null=True)),
                ('file_data', models.FileField(upload_to='tmp/%Y/%m/%d')),
            ],
        ),
    ]
