# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_senduser_user_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='aggregate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='balance',
            field=models.IntegerField(),
        ),
    ]
